# Copy to settings.toml if you prefer TOML over .env
device_name = "Pi-Fi Player"
volume_step = 5

client_id = "YOUR_SPOTIFY_CLIENT_ID"
redirect_uri = "http://pi.local:8080/callback"
scopes = "user-read-playback-state,user-modify-playback-state,playlist-read-private,playlist-read-collaborative,user-read-currently-playing"
